### ISSUE TITLE
Use of `args` on `runPipeline`

### ISSUE THREAD

**Issue by ramonemiliani93** [InsightSoftwareConsortium/itk-wasm#1062]
Hi 👋 

I'm currently facing an issue while attempting to execute a simple pipeline with a single image as input and a single image as output. Specifically, I'm uncertain about the appropriate value to assign to the `args` parameter in the `runPipeline` method.

Every attempt I've made so far has resulted in the following error message:
```
/ITK/Modules/IO/ImageBase/include/itkImageFileReader.hxx:261:
The file doesn't exist. 
```

Could someone provide guidance on how the args list should be utilized? There seems to be few examples demonstrating its usage, particularly in browser environments. I've experimented with setting the image name and utilizing the index, as demonstrated in this [example](https://wasm.itk.org/en/latest/cxx/tutorial/inputs_outputs.html#run-in-node-js), but without success.

Your assistance would be greatly appreciated!

#### Edit 1
I changed the `args` from the string index `"0"` to the integer value `0` and it seemed to go through the reader but still I get an error on the first filter:
```
ITK ERROR: OtsuThresholdImageFilter(0xc45968): Input Primary is required but not set.
```

**Comment by thewtex** [comment]
Hi @ramonemiliani93 ,

We now have a [tool to help generate JavaScript bindings](https://www.npmjs.com/package/create-itk-wasm). Testing and feedback is appreciated.

Currently, Windows support is [in progress, tracked here](#1000).
