### ISSUE TITLE
Handling negative indices on WebAssembly memory IO

### ISSUE THREAD

**Issue by ramonemiliani93** [InsightSoftwareConsortium/itk-wasm#1065]
Hi 👋

I've noticed a difference while working with padding filters, particularly when using WebAssembly memory IO versus the filesystem.

When employing ITK filters with padding, the image's origin is preserved, and negative indices handle padding. However, when saving images via the filesystem, metadata updates smoothly, while WebAssembly memory IO seems to miss the mark.

I've set up a quick example [here](https://github.com/ramonemiliani93/pad-bug) to illustrate. When running the pipeline with the WASI build, the image is correct, but in the browser, the origin behaves oddly.

I'm curious: should WebAssembly memory IO handle this, or is it the pipeline's job to manage negative indices and update the image origin?

Looking forward to your insights!

**Comment by thewtex** [comment]
Hello! :wave: :sun_with_face: 

> I've set up a quick example here to illustrate. When running the pipeline with the WASI build, the image is correct, but in the browser, the origin behaves oddly.

This is an outstanding example to illustrate the issue. Well done.

Yes, you have discovered a bug! :bug: The ITK-Wasm `Image` type does not include support for the `Index` that is adjusted by the ConstantPadImageFilter. Adjusting your demo to print the output image:

```
Image (0x2e048)
  RTTI typeinfo:   N3itk5ImageIhLj3EEE
  Reference Count: 1
  Modified Time: 30
  Debug: Off
  Object Name: 
  Observers: 
    none
  Source: (0x2de00) 
  Source output name: Primary
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 23
  UpdateMTime: 31
  RealTimeStamp: 0 seconds 
  LargestPossibleRegion: 
    Dimension: 3
    Index: [-3, -3, -3]
    Size: [9, 9, 9]
  BufferedRegion: 
    Dimension: 3
    Index: [-3, -3, -3]
    Size: [9, 9, 9]
  RequestedRegion: 
    Dimension: 3
    Index: [-3, -3, -3]
    Size: [9, 9, 9]
  Spacing: [1, 1, 1]
  Origin: [0, 0, 0]
  Direction: 
1 0 0
0 1 0
0 0 1

  IndexToPointMatrix: 
1 0 0
0 1 0
0 0 1

  PointToIndexMatrix: 
1 0 0
0 1 0
0 0 1

  Inverse Direction: 
1 0 0
0 1 0
0 0 1

  PixelContainer: 
    ImportImageContainer (0x2e258)
      RTTI typeinfo:   N3itk20ImportImageContainerImhEE
      Reference Count: 1
      Modified Time: 28
      Debug: Off
      Object Name: 
      Observers: 
        none
      Pointer: 0x2e2d8
      Container manages memory: true
      Size: 729
      Capacity: 729
```

The solution is to fix the `ImageToWasmImageFilter` to adjust the output origin when the LargestPossibleRegion's Index is not all zeros. The output origin can be determined by calling [`TransformIndexToPhysicalPoint`](https://itk.org/Doxygen/html/classitk_1_1ImageBase.html#a8360b9623d685997725c81c85716c4d2) with the input image's LargestPossibleRegion Index:

https://github.com/InsightSoftwareConsortium/itk-wasm/blob/3bd777e1225671090edb6e6a45a5a73eab07f5c8/include/itkImageToWasmImageFilter.hxx#L167

Could you please [submit a patch](https://wasm.itk.org/en/latest/development/hacking_itk_wasm.html)?
