### ISSUE TITLE
OSError: [Errno 30] Read-only file system: '/home/sbx_user1051'

### ISSUE THREAD

**Issue by pritamrungta** [InsightSoftwareConsortium/itk-wasm#1132]
I have deployed the code in AWS Lambda, and `import itkwasm` statement throws the above error.

Attached stack trace:
<img width="884" alt="image" src="https://github.com/InsightSoftwareConsortium/itk-wasm/assets/59230352/2ea02653-9ac6-482d-bde3-48a6bbd7236a">

**Comment by thewtex** [comment]
Thanks for the report.

We could do a few things:

- Default `_module_store_dir` to `None`, and only set it if `user_cache_dir("itkwasm"))` is writable.
- Fallback to a different directory (a directory in /tmp/?) to support AWS Lambda if this caching is useful for AWS Lambda.

**Comment by pritamrungta** [comment]
I think the second option seems more suitable in this case.
As a temporary workaround, I had got it working by setting env `HOME=/tmp`. But having this as a config setting in itk-wasm package would be nice.

**Comment by thewtex** [comment]
Please review / test #1134

**Comment by pritamrungta** [comment]
Looks good. 👍🏻
