### ISSUE TITLE
niftiReadImage dosen`t work

### ISSUE THREAD

**Issue by kaizibaby** [InsightSoftwareConsortium/itk-wasm#1146]
please tell me  why it dosen`t work..

###
mac chrome 
@itk-wasm/image-io version 1.2.0
###
import { niftiReadImage } from '@itk-wasm/image-io';
dom.addEventListener('change', async (e) => {
  const file = e.target.files[0];
  const arrayBuffer = await file.arrayBuffer();
  
  const data = await niftiReadImage(
      {
        data: new Uint8Array(arrayBuffer),
        path: file.name,
      },
      {
        webWorker: null,
      }
    )
  });

**Comment by thewtex** [comment]
Hi,

Nothing stands out from the code provided. More context is needed. Please provide a fully reproducible, simple, concise example along with details on the errors you are experiencing.
