### ISSUE TITLE
`--emscripten-docker-image` does not work on `itk-wasm pnpm-script`

### ISSUE THREAD

**Issue by ramonemiliani93** [InsightSoftwareConsortium/ITK-Wasm#1186]
Hi 👋

I am building a processing pipeline using the `itk-wasm pnpm-script build:emscripten` command. I am having some issues with the latest Emscripten image, so I tried using the `--emscripten-docker-image` flag to use a previous image that worked, but it still fetches the latest tag even though I have the target docker image locally. Thanks for the help 🙌

**Comment by thewtex** [comment]
Hi :-)

The emscripten docker image is currently configured in the `itk-wasm.emscripten-docker-image` property in the top level `package.json`. Here is an example:

https://github.com/InsightSoftwareConsortium/ITKIOOpenJPH/blob/d81f41ff6f181cc9f17f82e7206068cc68b90623/src/wasm/package.json#L9
