### ISSUE TITLE
`emscriptenModule.writeAsciiToMemory` is not a function

### ISSUE THREAD

**Issue by ramonemiliani93** [InsightSoftwareConsortium/ITK-Wasm#1187]
Hi 👋

I have a preprocessing pipeline I am building, and it worked using previous Docker images. It works on the tag `20240516-1a13e4ae` but breaks on the tag `20240516-32a1ffd9`. It seems both tags were published on the same day, but with the second one, I get the error `emscriptenModule.writeAsciiToMemory is not a function` when running my pipeline. Could you please point me to how to solve this issue? Thanks in advance 🙌

**Comment by thewtex** [comment]
Hola :wave: 

The docker image and the corresponding `itk-wasm` package version will both be bumped -- the docker image removed interfaces that emscripten deprecated, and the bindings defined in the `itk-wasm` package migrated accordingly.

**Comment by ramonemiliani93** [comment]
Perfect 💪 Thanks a lot Matt!
