### ISSUE TITLE
Case sensitive URLs

### ISSUE THREAD

**Issue by neurolabusc** [InsightSoftwareConsortium/ITK-Wasm#1189]
The [npm links](https://www.npmjs.com/package/@itk-wasm/image-io) for `💻 Live API Demo`  ` Documentation 📚` are broken. The links use lower-case `itk-wasm` but need to have some capital letters `ITK-Wasm`.

**Comment by thewtex** [comment]
@neurolabusc thanks for the note -- will be fixed with the next version bump.

**Comment by thewtex** [comment]
Addressed via #1195
