### ISSUE TITLE
Add acknowledgment of support by IDC to the dicom package

### ISSUE THREAD

**Issue by fedorov** [InsightSoftwareConsortium/ITK-Wasm#1207]
Here's the suggested wording - would be great to have this included in some README file in the repo and in the documentation.

> Development of this library was supported by [NCI Imaging Data Commons](https://imaging.datacommons.cancer.gov/), and has been funded in whole or in part with Federal funds from the National Cancer Institute, National Institutes of Health, under Task Order No. HHSN26110071 under Contract No. HHSN261201500003l.

**Comment by thewtex** [comment]
Done:

- [Python Docs](https://insightsoftwareconsortium.github.io/ITK-Wasm/dicom/py/docs/acknowledgments.html)
- [Python Package](https://pypi.org/project/itkwasm-dicom/)
- [JavaScript Docs](https://insightsoftwareconsortium.github.io/ITK-Wasm/dicom/ts/docs/#/?id=acknowledgments)
- [JavaScript Package](https://www.npmjs.com/package/@itk-wasm/dicom)
