### ISSUE TITLE
Published package @itk-wasm/downsample v1.4.1 is missing several files

### ISSUE THREAD

**Issue by Gabsha** [InsightSoftwareConsortium/ITK-Wasm#1220]
It appears that the published package on NPM is missing most of the files in the `dist/` folder, including the entrypoint.

Looking at [the published code for v1.4.1](https://www.npmjs.com/package/@itk-wasm/downsample/v/1.4.1?activeTab=code), the dist folder only contains the `pipelines/` folder, whereas [version 1.4.0 seems complete](https://www.npmjs.com/package/@itk-wasm/downsample/v/1.4.0?activeTab=code).

The @itk-wasm/dicom package v7.2.1 seems to have suffered the same fate.

**Comment by thewtex** [comment]
Hi @Gabsha,

Thanks for the note! I will publish a bump for both packages.

**Comment by thewtex** [comment]
Addressed with [@itk-wasm/dicom 7.2.2](https://www.npmjs.com/package/@itk-wasm/dicom?activeTab=code) and [@itk-wasm/downsample 1.4.2](https://www.npmjs.com/package/@itk-wasm/downsample?activeTab=code).
