### ISSUE TITLE
browser api in node packages?

### ISSUE THREAD

**Issue by sigmama** [InsightSoftwareConsortium/ITK-Wasm#1268]
Hello, is there a way to import browser apis from node module instead of including the bundled js files in html file and then access the browser apis with windows.itk?

**Comment by thewtex** [comment]
Hi,

I might not understand the question.

The packages export API's that work in either a Node.js or Browser environment. The APIs exposed are based on your project's build target.

Generally, Node.js does not provide the `window` interface.

**Comment by sigmama** [comment]
Hi @thewtex, after read through the example on vtkjs official site  (https://kitware.github.io/vtk-js/examples/ItkWasmGeometry.html) I was trying to directly import the readMeshArrayBuffer from itk@wasm with version 1.0.0-b.70 instead of use the umd file directly and found that browser apis are not exposed.
After read through the documents on itk-wasm website, I've realised that I can use the readMesh method now with the individual @itk-wasm/mesh-io package. So basically I do not have other concern now and will close this issue.
