### ISSUE TITLE
Problem with compressed DICOM

### ISSUE THREAD

**Issue by Athius** [InsightSoftwareConsortium/itk-wasm#389]
Hi everyone,
I tried to load a Dicom inside the example [UMD](https://insightsoftwareconsortium.github.io/itk-js/examples/umd.html) but nothing append (the loop circle continue indefinitely).

Is the JPEG 2000 is still not supported?
From the issue #145, I'm not sure if it's supported or not.

Thank you 

Edit: I can provide you a problematic dicom

**Comment by thewtex** [comment]
Hi @Athius ,

Yes, JPEG 2000 is now supported.

Does the file load with: https://kitware.github.io/itk-vtk-viewer/index.html ?

**Comment by thewtex** [comment]
Please re-open if still an issue with `itk-wasm` `1.0.0.a10` or later.
