### ISSUE TITLE
readImageDICOMFileSeries not work in official example

### ISSUE THREAD

**Issue by MountainAndMorning** [InsightSoftwareConsortium/itk-wasm#449]
I changed the official webpack example from `readFile`  to `readImageDICOMFileSeries`, but got an error in the console of  chrome. The same situation also occur in my electron+vue project. It seems this is a bug of itk-wasm. In the other hand, the ParaView Glance is too complicate to understand the config of itk-wasm for a vue project. I suggest you  to provide a simple example for vue or electron+vue, thanks.

![截屏2021-11-16 上午9 13 03](https://user-images.githubusercontent.com/30199027/141877817-d877eb21-4ad6-47eb-ab47-b7a2c3a5c5c0.png)

```js
import { readImageDICOMFileSeries } from 'itk-wasm/dist/browser/index.js'
import curry from 'curry'

const outputFileInformation = curry(function outputFileInformation (outputTextArea, event) {
  outputTextArea.textContent = 'Loading...'

  const dataTransfer = event.dataTransfer
  const files = event.target.files || dataTransfer.files

  // const viewerElement = document.getElementById('viewer')
  // !!viewerElement && itkVtkViewer.createViewerFromFiles(viewerElement, files)

  return readImageDICOMFileSeries(files, true)
    .then(function ({ image, mesh, polyData, webWorker }) {
      webWorker.terminate()
      const imageOrMeshOrPolyData = image || mesh || polyData

      function replacer (key, value) {
        if (!!value && value.byteLength !== undefined) {
          return String(value.slice(0, 6)) + '...'
        }
        return value
      }
      outputTextArea.textContent = JSON.stringify(imageOrMeshOrPolyData, replacer, 4)
    })
})

export { outputFileInformation }
```

**Comment by thewtex** [comment]
Hi,

`readImageDICOMFileSeries` is not yet available in itk-wasm per #446 .

We will create a simple Vue example.

**Comment by MountainAndMorning** [comment]
Thanks for your help, look forward to the powerful `readImageDICOMFILESeries` function.

**Comment by thewtex** [comment]
`readImageDICOMFileSeries` has been updated for `itk-wasm` in version `1.0.0.a10`

**Comment by MountainAndMorning** [comment]
Thanks for your work. I have tried the `readImageDICOMFileSeries` function. It is very fast compared to read the DICOM series in sequence.

**Comment by thewtex** [comment]
@MountainAndMorning great to hear.
