### ISSUE TITLE
vtkArrayTypeToItkComponentType

### ISSUE THREAD

**Issue by MountainAndMorning** [InsightSoftwareConsortium/itk-wasm#452]
When we convert the vtk image to itk image, we must convert the vtk array type to the itk component type by the map `vtkArrayTypeToItkComponentType`. 

In MacOS, the itk component type ends with '_t' will work as below:

```js
var vtkArrayTypeToItkComponentType = new Map([['Uint8Array', 'uint8_t'], ['Int8Array', 'int8_t'], ['Uint16Array', 'uint16_t'], ['Int16Array', 'int16_t'], ['Uint32Array', 'uint32_t'], ['Int32Array', 'int32_t'], ['Float32Array', 'float'], ['Float64Array', 'double']]);
```

In Windows, we must remove the postfix or you will get an error : `Unknown IO component type`
```js
var vtkArrayTypeToItkComponentType = new Map([['Uint8Array', 'uint8'], ['Int8Array', 'int8'], ['Uint16Array', 'uint16_], ['Int16Array', 'int16'], ['Uint32Array', 'uint32'], ['Int32Array', 'int32'], ['Float32Array', 'float'], ['Float64Array', 'double']]);
```

MacOS: 11.4
Windows: 10

vtk.js: ^11.14.0
itk-wasm: ^1.0.0-a.8

**Comment by thewtex** [comment]
It should be the latter. Addressed in vtk.js in https://github.com/Kitware/vtk-js/pull/2310
