### ISSUE TITLE
Where is documentation?

### ISSUE THREAD

**Issue by stounej** [InsightSoftwareConsortium/itk-wasm#463]
Hey,

I'm getting ERROR 404 when trying to access to your documentation page, I really need  DICOM series to be rendered as single volume, I don't know how

Thankq

**Comment by thewtex** [comment]
The documentation is here: https://insightsoftwareconsortium.github.io/itk-wasm/

**Comment by stounej** [comment]
Sorry but I can't see how to use itk-wasm, I need detailled docs, the functions we can use in itk-wasm.. thank you so much
