### ISSUE TITLE
Remove dependency from node built-ins

### ISSUE THREAD

**Issue by FezVrasta** [InsightSoftwareConsortium/itk-wasm#470]
webpack 5 doesn't polyfill node built-ins anymore (https://webpack.js.org/blog/2020-10-10-webpack-5-release/#automatic-nodejs-polyfills-removed)

This library seems to depend on many modules that require these polyfills, would you consider to replace them with browser-friendly versions?

**Comment by thewtex** [comment]
Along with a recent update from @floryst in #471 , you can now import from a browser-only index

```
import { IntTypes } from 'itk/browser/index.js'
```

This index does not depend recursively on any Node-dependent imports, so there is no longer need to provide polyfills or shims when building with WebPack for the browser.

**Comment by thewtex** [comment]
@FezVrasta great suggestion!  Please take a look at https://github.com/InsightSoftwareConsortium/itk-wasm/pull/494
