### ISSUE TITLE
Add `main` entry to itk-image-io package.json

### ISSUE THREAD

**Issue by FezVrasta** [InsightSoftwareConsortium/itk-wasm#477]
Without a `main` entry it's impossible to use `require.resolve` to find the location of the package, this is very helpful in the webpack configuration needed to copy the files to the public folder.

Without this, we are forced to make the assumption the package will be available on a specific `node_modules` folder, but it doesn't play nicely with monorepos, hoisting, etc

**Comment by thewtex** [comment]
@FezVrasta would you like to create a patch for this?

Perhaps we should copy *./dist/io/internal/ImageIOIndex.js* in into *./dist/image-io/index.js* and use this for `main`? Will this address your issue?

**Comment by FezVrasta** [comment]
For my specific issue even an empty index.js file would work, I just need something attached to `main` so that `require.resolve` can find it.

**Comment by thewtex** [comment]
@FezVrasta Addressed in #484
