### ISSUE TITLE
Missing alias configuration in webpack example

### ISSUE THREAD

**Issue by FezVrasta** [InsightSoftwareConsortium/itk-wasm#478]
Hi, I'm trying to configure webpack 5 but in the example I don't see how to configure the alias to `itkConfig.js` I want to point to my local files rather than the CDN.

https://github.com/InsightSoftwareConsortium/itk-wasm/blob/master/examples/Webpack/webpack.config.js

May you advise? Thanks!

**Comment by thewtex** [comment]
Hi @FezVrasta , yes, please take a look at #481
