### ISSUE TITLE
Provide a readImageDICOMArrayBufferSeries

### ISSUE THREAD

**Issue by FezVrasta** [InsightSoftwareConsortium/itk-wasm#480]
Our pipeline looks like the following:

1. `fetch` a `.tar` file containing several DICOM files
2. untar the DICOM files with `js-untar`
3. pipe each of them into a `File` instance
4. pass the list of `File`s to `readImageDICOMFileSeries`

It'd be extremely useful if itk-wasm exposed a function similar to `readImageDICOMFileSeries` but that accepts a list of `ArrayBuffer`s, since that's what we already receive from `js-untar`, this way the logic would look like this:

1. `fetch` a `.tar` file containing several DICOM files
2. untar the DICOM files with `js-untar`
3. pass the list of `ArrayBuffer`s to `readImageDICOMArrayBufferSeries`

The process that creates the "fake" `File` instances can take a lot of time (400ms on a ~300 DICOMs list)

Is there any technical reason that prevents this from being added?

Thanks!

**Comment by thewtex** [comment]
@FezVrasta added in #482

**Comment by FezVrasta** [comment]
I tested it locally and it seems to work, thanks!

Do you think you could do the same for `readDICOMTags`? I see a lot of calls to `readAsArrayBuffer` that should be unnecessary given I already have the arrayBuffers available.

**Comment by thewtex** [comment]
@FezVrasta excellent!

Yes, will-do for `readDICOMTags`.

**Comment by thewtex** [comment]
Done in https://github.com/InsightSoftwareConsortium/itk-wasm/pull/492
