### ISSUE TITLE
Property ./index.d.ts is not allowed.

### ISSUE THREAD

**Issue by FezVrasta** [InsightSoftwareConsortium/itk-wasm#495]
Hi, opening the package.json I get a warning on `exports -> . -> ./index.d.ts`: "Property ./index.d.ts is not allowed."

1. Do you think it should be just `index.d.ts` instead?
2. Is it needed? I think `exports` should only list "real" javascript files, not type definitions, that are resolved by tsc

**Comment by thewtex** [comment]
Hi,

I added this because it was present in other packages -- we can remove it if it is causing issues.
