### ISSUE TITLE
Performance issue for large itk images (Reader and Writer)

### ISSUE THREAD

**Issue by Guzzler** [InsightSoftwareConsortium/itk-wasm#524]
#include<chrono>

using namespace std::chrono;
#include "itkImage.h"

#include "itkImageFileReader.h"
#include "itkImageFileWriter.h"

int main(int argc, char *argv[])
{
  auto start = high_resolution_clock::now();
  if (argc < 3)
  {
    std::cerr << "Missing Parameters " << std::endl;
    std::cerr << "Usage: " << argv[0];
    std::cerr
        << "inputImage  outputImage"
        << std::endl;
    return EXIT_FAILURE;
  }

  using InternalPixelType = float;
  constexpr unsigned int Dimension = 3;
  using InternalImageType = itk::Image<InternalPixelType, Dimension>;

  using OutputPixelType = float;
  using OutputImageType = itk::Image<OutputPixelType, Dimension>;

  using ReaderType = itk::ImageFileReader<InternalImageType>;
  using WriterType = itk::ImageFileWriter<OutputImageType>;

  auto reader = ReaderType::New();
  auto writer = WriterType::New();

  reader->SetFileName(argv[1]);
  writer->SetFileName(argv[2]);

  writer->SetInput(reader->GetOutput());
  
  try
  {
    writer->Update();
  }
  catch (const itk::ExceptionObject &excep)
  {
    std::cerr << "Exception caught !" << std::endl;
    std::cerr << excep << std::endl;
  }
  auto stop = std::chrono::high_resolution_clock::now();

  auto duration = duration_cast<microseconds>(stop - start);
 
  std::cout << "Time taken by function: "
        << duration.count() << " microseconds" << std::endl;

  return EXIT_SUCCESS;
}`

**Comment by Guzzler** [comment]
Here is a basic example of the cxx pipeline that i built using itk-js version 14.1.1.
A simple ITK image with an arraybuffer of length (512x512x200) is taking 6 seconds to execute while using runPipelineBrowser. Is there anything that is being done wrong? I am reading and writing to a file called 'input.json' and 'output.json' respectively and passing both as ITKImage objects. Would appreciate some help on why it takes that long to simply read and write the files and how this can be optimized.

**Comment by thewtex** [comment]
@Guzzler please try itk-wasm :-)

**Comment by Guzzler** [comment]
@thewtex I had earlier attempted to build using itk-wasm but it was failing so i defaulted to itk.js 14.1.1. will the speed up with itk wasm be significant?

**Comment by thewtex** [comment]
Yes, absolutely :zap:

**Comment by thewtex** [comment]
@Guzzler here is how to write the code for itk-wasm:

https://github.com/InsightSoftwareConsortium/itk-wasm/blob/master/test/pipelines/MeshReadWritePipeline/MeshReadWriteTest.cxx

Replace `Mesh` with `Image`.

**Comment by Guzzler** [comment]
Thanks a ton @thewtex . Can i use the connectedthresoldFilter and other header files similarly as before?

**Comment by thewtex** [comment]
@Guzzler yes. Interested to hear the delta in performance you experience.

**Comment by Guzzler** [comment]
Thanks a ton!
 @thewtex will give it a whirl and keep you updated.

**Comment by thewtex** [comment]
CC @finetjul

**Comment by Guzzler** [comment]
@thewtex Im facing this issue on the build step 
```

CMake Error at /ITK/CMake/ITKModuleAPI.cmake:78 (message):
  No such module: "BridgeJavaScript"
Call Stack (most recent call first):
  /ITK/CMake/ITKModuleAPI.cmake:31 (itk_module_load)
  /ITK/CMake/ITKModuleAPI.cmake:129 (_itk_module_config_recurse)
  /ITK-build/ITKConfig.cmake:86 (itk_module_config)
  CMakeLists.txt:11 (find_package)
```
My current CMakeLists.txt file looks something like this. This seems to work fine with itk-js. Here my goal is to prebuild these wasm files and then execute them similarly in a webapp using run pipeline browser.

```
cmake_minimum_required(VERSION 3.10)

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "../Pipelines/")

project(Test)

set(io_components ITKImageIO)
if(EMSCRIPTEN)
  set(io_components BridgeJavaScript)
endif()
find_package(ITK REQUIRED
  COMPONENTS ${io_components}
    ITKSmoothing
    ITKLabelVoting
    ITKRegionGrowing
    ITKCurvatureFlow
  )
include(${ITK_USE_FILE})

set(test_SRCS test.cxx)
if(EMSCRIPTEN)
  include(ITKBridgeJavaScript)
  web_add_executable(test ${test_SRCS})

else()
  add_executable(test ${test_SRCS})
endif()

target_link_libraries(test ${ITK_LIBRARIES})
```
Any pointers on why this may be happening? has BridgeJavascript been removed entirely? Couldnt find any info on the same in the migration from itk-js to itk-wasm

**Comment by Guzzler** [comment]
Changed the name to ITKWebAssemblyInterface but now my CMakeFile looks like this - 



```
cmake_minimum_required(VERSION 3.16)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "../Pipelines/")

project(Test)

set(io_components ITKImageIO)
if(EMSCRIPTEN)
  set(io_components WebAssemblyInterface)
endif()
find_package(ITK REQUIRED
  COMPONENTS ${io_components}
    ITKSmoothing
    ITKLabelVoting
    ITKRegionGrowing
    ITKCurvatureFlow
  )
include(${ITK_USE_FILE})

set(test_wasm_SRCS testwasm.cxx)
if(EMSCRIPTEN)
  include(ITKWebAssemblyInterface)
  web_add_executable(testwasm ${test_wasm_SRCS})

else()
  add_executable(testwasm ${test_wasm_SRCS})
endif()

target_link_libraries(testwasm ${ITK_LIBRARIES})
```
and my cxx file looks like this.

```
#include "itkImage.h"
#include "itkInputImage.h"
#include "itkOutputImage.h"
#include "itkPipeline.h"

int main( int argc, char * argv[] )
{
  itk::wasm::Pipeline pipeline("A test for reading and writing images", argc, argv);

  using PixelType = float;
  constexpr unsigned int Dimension = 3;
  using ImageType = itk::Image< PixelType, Dimension >;

  using InputImageType = itk::wasm::InputImage<ImageType>;
  InputImageType inputImage;
  pipeline.add_option("InputImage", inputImage, "The input mesh")->required();

  using OutputImageType = itk::wasm::OutputImage<ImageType>;
  OutputImageType outputImage;
  pipeline.add_option("OutputImage", outputImage, "The output mesh")->required();

  ITK_WASM_PARSE(pipeline);

  outputImage.Set(inputImage.Get());

  return EXIT_SUCCESS;
}
```

But still getting an error on the import of ItkInputImage.h

```
In file included from /work/src/libs/DicomTool/itk/testwasm.cxx:20:
In file included from /ITKWebAssemblyInterface/include/itkInputImage.h:26:
In file included from /ITKWebAssemblyInterface/include/itkWASMImageToImageFilter.h:101:
In file included from /ITKWebAssemblyInterface/include/itkWASMImageToImageFilter.hxx:25:
/ITKWebAssemblyInterface/include/itkWASMMapComponentType.h:88:37: error: constexpr variable 'ComponentString' must be initialized by a constant expression
  static constexpr std::string_view ComponentString = "uint64";
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~
/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1/__string:508:10: note: non-constexpr function 'length' cannot be used in a constant expression
  return _Traits::length(__s);
         ^
/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1/string_view:275:31: note: in call to '__char_traits_length_checked(&"uint64"[0])'
        : __data(__s), __size(_VSTD::__char_traits_length_checked<_Traits>(__s)) {}
                              ^
/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1/__config:812:15: note: expanded from macro '_VSTD'
#define _VSTD std::_LIBCPP_ABI_NAMESPACE
              ^
/ITKWebAssemblyInterface/include/itkWASMMapComponentType.h:88:55: note: in call to 'basic_string_view(&"uint64"[0])'
  static constexpr std::string_view ComponentString = "uint64";
                                                      ^
/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1/__string:338:5: note: declared here
    length(const char_type* __s)  _NOEXCEPT {return __builtin_strlen(__s);}
```

**Comment by Guzzler** [comment]
@thewtex After multiple rounds of firefighting, I have finally gotten the build to run and the code to compile to wasm. I am now trying to run it within my webapp using my craco config with create react app.

However when i am now getting two main issues - 
in LoadEmscriptenModule.js

```

import fs from 'fs';
// Workaround for EXPORT_ES6
// https://github.com/emscripten-core/emscripten/issues/11792
import { dirname } from 'path';
import { createRequire } from 'module';
globalThis.__dirname = dirname(import.meta.url);
globalThis.require = createRequire(import.meta.url);
```

createRequire is undefined causing the entire module to crash my app.

If this is removed (thought it might be a work around that is not required anymore), things seem to work till the point where I call my wasm file.

At that point I get this NetworkError on pipeline.worker.js even though the file exists in the right place.

```
Uncaught (in promise) 
Object { message: "A network error occurred.", stack: "e/<@http://localhost:3000/itk/web-workers/min-bundles/pipeline.worker.js:1:74869\nf@http://localhost:3000/itk/web-workers/min-bundles/pipeline.worker.js:1:1635\nc/i._invoke</<@http://localhost:3000/itk/web-workers/min-bundles/pipeline.worker.js:1:1424\nO/</<@http://localhost:3000/itk/web-workers/min-bundles/pipeline.worker.js:1:2064\ne@http://localhost:3000/itk/web-workers/min-bundles/pipeline.worker.js:1:66\nu@http://localhost:3000/itk/web-workers/min-bundles/pipeline.worker.js:1:270\n" }
```

My craco config is shown below.

```
const CracoVtkPlugin = require('craco-vtk');

const CopyPlugin = require('copy-webpack-plugin');

const path = require('path');
const wasmExtensionRegExp = /\.wasm$/;
// const { addBeforeLoader, loaderByName } = require('@craco/craco');
const itkConfig = path.resolve(__dirname, 'src', 'libs', 'itkConfig.js');

module.exports = {
  webpack: {
    configure: (webpackConfig, { env, paths }) => {
      // Emscripten uses import.meta
      webpackConfig.module.rules.push({
        test: /\.js$/,
        loader: require.resolve('@open-wc/webpack-import-meta-loader'),
      });

      webpackConfig.module.rules.push({
        test: /\.js$/,
        loader: 'babel-loader',
      });

      webpackConfig.module.rules.forEach((rule) => {
        (rule.oneOf || []).forEach((oneOf) => {
          if (oneOf.loader && oneOf.loader.indexOf('file-loader') >= 0) {
            // make default file-loader ignore WASM files
            oneOf.exclude.push(wasmExtensionRegExp);
          }
        });
      });

      // We want to provide "require('somefile.wasm')" as Emscripten locateFile.
      // This makes sure files required this way are not altered.
      webpackConfig.module.rules.push({
        test: /\.wasm$/,
        type: 'javascript/auto',
        include: path.resolve(__dirname, 'src'),
        loaders: 'file-loader',
        options: {
          name: '[name].[hash:8].[ext]',
        },
      });

      webpackConfig.performance = {
        maxAssetSize: 10000000,
      };
      const oldalias = webpackConfig.resolve.alias;

      webpackConfig.resolve.alias = {
        ...oldalias,
        '../itkConfig.js': itkConfig,
        '../../itkConfig.js': itkConfig,
      };

      const oldplugins = webpackConfig.plugins;

      webpackConfig.plugins = [
        ...oldplugins,
        new CopyPlugin({
          patterns: [
            {
              from: path.join(__dirname, 'node_modules', 'itk-wasm', 'dist', 'web-workers'),
              to: path.join(__dirname, 'dist', 'itk', 'web-workers'),
            },
            {
              from: path.join(__dirname, 'node_modules', 'itk-image-io'),
              to: path.join(__dirname, 'dist', 'itk', 'image-io'),
            },
            {
              from: path.join(__dirname, 'node_modules', 'itk-mesh-io'),
              to: path.join(__dirname, 'dist', 'itk', 'mesh-io'),
            },
          ],
        }),
      ];
      return webpackConfig;
    },
  },
  plugins: [
    {
      plugin: CracoVtkPlugin(),
    },
  ],
```

Is there any assistance you might be able to provide for this?

**Comment by Guzzler** [comment]
And i think the first issue is due to the way the webpack dev server reads imports. As long as I have even one import of itk-wasm in my file, on runtime my webapp breaks with the error stated above. Removing that one line manually seems to fix it. Ignoring that issue, I am carrying on trying to get a minimum working example and my imports are as per the normal guidelines given above, here is the code
```

import { InterfaceTypes, runPipeline } from 'itk-wasm';

// and it is used like this -
 let itkImage = ITKHelper.convertVtkToItkImage(imageData);
  const desiredOutputs = [{ type: InterfaceTypes.Image }];
  const inputs = [{ type: InterfaceTypes.Image, data: itkImage }];

const result = await runPipeline(
    // null to create webworker during execution
    toolManager.webWorker,
    // built file name
    'http://localhost:3000/itk/pipelines/testwasm',
    // arguments to C++ file
    ['0', '0'],
    // args - [inputImage  outputImage]
    desiredOutputs,
    inputs,
  );

```
I tried changing my itk config as you suggested. Here is the itkConfig File
```

const version = '1.0.0-b.3';

const itkConfig = {
  webWorkersUrl: `https://cdn.jsdelivr.net/npm/itk-wasm@${version}/dist/web-workers`,
  imageIOUrl: `https://cdn.jsdelivr.net/npm/itk-image-io@${version}`,
  meshIOUrl: `https://cdn.jsdelivr.net/npm/itk-mesh-io@${version}`,
  pipelinesUrl: '/itk/pipelines',

};
export default itkConfig;
```
This seems to fix the network but now i am getting another issue -

```
{
  "message": "t.buffer is undefined",
  "stack": "IP@blob:http://localhost:3000/b62ef149-3f97-4da5-b1ad-4be09cd55eb4:1:110022\nAP/<@blob:http://localhost:3000/b62ef149-3f97-4da5-b1ad-4be09cd55eb4:1:111147\nAP@blob:http://localhost:3000/b62ef149-3f97-4da5-b1ad-4be09cd55eb4:1:110666\ne/<@blob:http://localhost:3000/b62ef149-3f97-4da5-b1ad-4be09cd55eb4:1:127312\nf@blob:http://localhost:3000/b62ef149-3f97-4da5-b1ad-4be09cd55eb4:1:1635\nc/i._invoke</<@blob:http://localhost:3000/b62ef149-3f97-4da5-b1ad-4be09cd55eb4:1:1424\nO/</<@blob:http://localhost:3000/b62ef149-3f97-4da5-b1ad-4be09cd55eb4:1:2064\ne@blob:http://localhost:3000/b62ef149-3f97-4da5-b1ad-4be09cd55eb4:1:66\nu@blob:http://localhost:3000/b62ef149-3f97-4da5-b1ad-4be09cd55eb4:1:270\nt/</<@blob:http://localhost:3000/b62ef149-3f97-4da5-b1ad-4be09cd55eb4:1:329\nt/<@blob:http://localhost:3000/b62ef149-3f97-4da5-b1ad-4be09cd55eb4:1:209\nHP@blob:http://localhost:3000/b62ef149-3f97-4da5-b1ad-4be09cd55eb4:1:128167\n$P@blob:http://localhost:3000/b62ef149-3f97-4da5-b1ad-4be09cd55eb4:1:127156\ne/<@blob:http://localhost:3000/b62ef149-3f97-4da5-b1ad-4be09cd55eb4:1:129428\nf@blob:http://localhost:3000/b62ef149-3f97-4da5-b1ad-4be09cd55eb4:1:1635\nc/i._invoke</<@blob:http://localhost:3000/b62ef149-3f97-4da5-b1ad-4be09cd55eb4:1:1424\nO/</<@blob:http://localhost:3000/b62ef149-3f97-4da5-b1ad-4be09cd55eb4:1:2064\ne@blob:http://localhost:3000/b62ef149-3f97-4da5-b1ad-4be09cd55eb4:1:66\nu@blob:http://localhost:3000/b62ef149-3f97-4da5-b1ad-4be09cd55eb4:1:270\n"
}
```

Any ideas on what i could be doing wrong ?

**Comment by thewtex** [comment]
> And i think the first issue is due to the way the webpack dev server reads imports. 

Updating to the latest itk-wasm and webpack hopefully addresses this per https://github.com/InsightSoftwareConsortium/itk-wasm/issues/470

> {
  "message": "t.buffer is undefined",
  "stack": "IP@blob:http://localhost

Checking the Chrome Dev Tools *Network* tab may reveal the issue. I had a similar error recently where jsDelivr was responding with a 403. I do not know if this is the case in your setup, but it may help to look.

Also, a hack to get a more debuggable version of the worker (non-minified) is to change these lines: https://github.com/InsightSoftwareConsortium/itk-wasm/blob/51fd6fb0725dd5dc116fab918948a25b876ea48e/src/core/internal/createWebWorkerPromise.ts#L31-L33. With recent refactoring, we only have one worker -- I will improve this so that a non-minified worker can be set directly in `itkConfig`.

**Comment by Guzzler** [comment]
@thewtex The network tab is all 200. on doing a debugger run through the code i discovered that the image.direction is not adding anything as it does not contain a `buffer` or `byteLength` key and hence never gets added in the transferables as GetTransferable returns null. Could this be the cause of this issue?

I managed to fix the first issue by directly importing only runPipeline from 'itk-wasm/dist/browser' but will upgrade to fix it none the less.

I will try to run the webworker promise in debug mode and try. Thanks! Do let me know if you have any more thoughts

**Comment by Guzzler** [comment]
The above issue seems to be an issue with the ITKHelper code in the vtk-js version im using. this converts direction to an object instead of the expected Float64Array as per your documentation. I am manually setting it to the ArrayBuffer value and that fixes the undefined error but still getting another error now 
with the execution of the pipeline. Will try the debug mode and let you know how it goes! Thanks.

**Comment by Guzzler** [comment]
@thewtex any idea how i can build the module in debug mode as prompted below -
![Screenshot from 2022-03-12 18-25-15](https://user-images.githubusercontent.com/12707741/158018783-848d9f3d-1755-458f-b3de-d076841034cf.png)

**Comment by thewtex** [comment]
> contain a buffer or byteLength key and hence never gets added in the transferables as GetTransferable returns null. Could this be the cause of this issue?

> The above issue seems to be an issue with the ITKHelper code in the vtk-js version im using. this converts direction to an object instead of the expected Float64Array as per your documentation. 

@Guzzler great detective work! :detective: This should be address with [vtk.js-23](https://github.com/Kitware/vtk-js/releases/tag/v23.0.0) which adds https://github.com/kitware/vtk-js/commit/407d97cae18d9ac10b61cba7a4cd2f4ee8e4f68b

>  any idea how i can build the module in debug mode as prompted below -

To get the exception message, build with `itk-wasm build -- -DCMAKE_BUILD_TYPE=Debug`. More information on how to get a debugger session:

https://wasm.itk.org/examples/debugging.html#Debugging-WebAssembly

**Comment by Guzzler** [comment]
Thanks! i'll take a look at these docs but after adding the debugger i'm getting an error as shown below. Seems to be in the runtime of the C++ file. As i am able to run a few log statements before that. Error - Unexpected Component Type.
![Screenshot from 2022-03-14 13-11-06](https://user-images.githubusercontent.com/12707741/158126894-f7a56c29-798a-4d30-8586-227cab1ac628.png)

Is this a common error? And if so what might be the cause of this?

As suggested by you above I took the mesh example and changed it to just do a simple read/write of an image as shown below. 
Would really appreciate if you could give me some pointers on what could be going wrong.

```
#include "itkImage.h"
#include "itkInputImage.h"
#include "itkOutputImage.h"
#include "itkPipeline.h"

int main( int argc, char * argv[] )
{
  std::cout << "Hello World" << std::endl;
  itk::wasm::Pipeline pipeline("A test for reading and writing images", argc, argv);

  using PixelType = float;
  constexpr unsigned int Dimension = 3;
  using ImageType = itk::Image< PixelType, Dimension >;

  using InputImageType = itk::wasm::InputImage<ImageType>;
  InputImageType inputImage;
  pipeline.add_option("InputImage", inputImage, "The input image")->required();

  using OutputImageType = itk::wasm::OutputImage<ImageType>;
  OutputImageType outputImage;
  pipeline.add_option("OutputImage", outputImage, "The output image")->required();

  ITK_WASM_PARSE(pipeline);

  outputImage.Set(inputImage.Get());

  return EXIT_SUCCESS;
}
```

**Comment by Guzzler** [comment]
Thanks a ton @thewtex for all your help. after some more firefighting I was finally able to execute the example for read and write. The function executed on an average in 200 microseconds or 0.2s to read/write a file of size 512x512x200. This was a stark improvement from the 5.7s it took earlier in itk-js. 

My use cases are slightly more complex and might take some more firefighting on issues but thank you again for all your help!

**Comment by thewtex** [comment]
@Guzzler fantastic to hear your success!! Your persistence and patience are impressive!

Good to know the performance improvements you have experienced with itk-wasm vs itk.js. 0.2 vs 5.7 sec is certainly a stark improvement :zap: !

`itk::wasm::Pipeline` documentation is forthcoming and extremely important -- I would appreciate your feedback as it comes in!

**Comment by Guzzler** [comment]
@thewtex Of course would gladly provide feedback and help in any way required. Thanks again!
