### ISSUE TITLE
How to read a .mhd file?

### ISSUE THREAD

**Issue by soapYE** [InsightSoftwareConsortium/itk-wasm#557]
Hi, I am trying to follow the UMD example and read a .mhd file.

After searching a lot I realized that the .mhd file is just a header file and the real image data is stored in the .raw file. I can use vtk python and 3D slicer to read the .mhd file with .raw file in the same directory.

However I have no idea how I can do that with javascript? Using the <input type="file"> I can select .mhd file but the corresponding .raw file is missing and I got this error message.
![image](https://user-images.githubusercontent.com/59732517/161903795-b93ae26e-2c9f-43c3-847d-2fde116539ae.png)

Could you please give me any suggestion?

**Comment by thewtex** [comment]
A quick work around is to save  a `.mha`, which will be a single file instead of a `.mhd`, `.raw` pair.

**Comment by soapYE** [comment]
Thank you!
