### ISSUE TITLE
writeArrayBuffer and readArrayBuffer change properties of image 

### ISSUE THREAD

**Issue by WillCMcC** [InsightSoftwareConsortium/itk-wasm#578]
```
  // Read series
  const { image } = await readImageDICOMFileSeries(files);

  console.log(image.direction.toString()); // 0,0,-1,1,0,0,0,-1,0

  // serialize and deserialize the series
  const { arrayBuffer: itkImageArrayBuffer } =
    await writeArrayBuffer(null, image,'test.mha', "", false);

  const { image: cachedImage } = await readArrayBuffer(
    null,
    itkImageArrayBuffer,
    'test.mha'
  );

  console.log(cachedImage.direction.toString()); // 0,1,0,0,0,-1,-1,0,0
  ```

**Comment by jadh4v** [comment]
Noted. I am looking into this.

**Comment by thewtex** [comment]
@jadh4v what did you find?

**Comment by jadh4v** [comment]
I have done some digging but not found anything solid yet.

**Comment by jadh4v** [comment]
@sankhesh we should probably close this issue. Do we need some documentation in the code for noting this issue?

**Comment by sankhesh** [comment]
The primary issue here is the `itkMetaImageIO` does not take **AnatomicalOrientation** into consideration. This issue is documented in detail [here](https://github.com/InsightSoftwareConsortium/ITK/issues/1017).

**Comment by sankhesh** [comment]
@thewtex I don't have permissions. Could you please close this? The earlier comment explains why this issue cannot be fixed.

**Comment by thewtex** [comment]
@sankhesh thanks for the follow-up.

You should receive an invite for permissions, but closing for now.
