### ISSUE TITLE
How can i support unstructured grid by itk-wasm?

### ISSUE THREAD

**Issue by supriome** [InsightSoftwareConsortium/itk-wasm#582]
@finetjul said that technically vtk-wasm can support unstrucured grid in this reply. [https://github.com/Kitware/vtk-js/issues/976#issuecomment-1156437119](https://github.com/Kitware/vtk-js/issues/976#issuecomment-1156437119)

But this is no any document tell me how to start? so I want to know if you can write a participation guidelines for people who want to contribute.

Thanks.

**Comment by thewtex** [comment]
Hi @supriome ,

Thanks for offering to contribute! We follow ITK's [Code of Conduct](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CODE_OF_CONDUCT.md) and some general guidance an [contributing to itk-wasm is in the docs](https://wasm.itk.org/docs/hacking_itk_wasm.html). Please let us know if you there is missing information.

Is your goal to read a VTK UnstructuredGrid legacy and render it in vtk.js?

**Comment by supriome** [comment]
Yes, I need readerUnstructuredGrid and then make a clip plane.

**Comment by acse-xw321** [comment]
@thewtex Hi, do you think it is possible to use webassembly to support unstructured gird or other data format, I'm trying to do this.

**Comment by supriome** [comment]
@acse-xw321 I am trying the solution of use webassembly to support unstructured grid, but i have some problem that when i read an unstructured grid vtk file, then i must use the same webassembly exported `vtkSDL2OpenGLRenderWindow` to render that reader into window, I don't know if is possible to integrate with vtk.js `vtkFullScreenRenderWindow` and `vtkMapper`, I tried, but all failed.

**Comment by thewtex** [comment]
@supriome @acse-xw321 after finishing a VTK Unstructured Grid reader, this feature will be available.

**Comment by supriome** [comment]
@thewtex  I noticed that this requirement has been in development for a long time, is there a specific time frame for completion?  #https://github.com/Kitware/vtk-js/issues/976

**Comment by thewtex** [comment]
@supriome most of the hard work has been done. See, e.g.: https://kitware.github.io/vtk-js/examples/ItkWasmGeometry.html. A reasonable estimate is the end of August.

**Comment by supriome** [comment]
Thank you very much, I achieved it temporarily by other means. But still looking forward to seeing how you guys implement it.
