### ISSUE TITLE
16-bit pixel containers being read into 32-bit containers

### ISSUE THREAD

**Issue by floryst** [InsightSoftwareConsortium/itk-wasm#622]
Reported by @WillCMcC 

Expected (from pydicom):
![image](https://user-images.githubusercontent.com/1812167/186681160-01f71ab0-eb2c-4ce7-aee5-bef228655100.png)

Actual (from itk-wasm):
![image](https://user-images.githubusercontent.com/1812167/186681408-88a14634-9987-497c-bd6a-9bb23d3c1893.png)

**Comment by thewtex** [comment]
This is required with non-trivial rescale slope / intercept to prevent overflow.
