### ISSUE TITLE
Old version hardcoded 

### ISSUE THREAD

**Issue by WillCMcC** [InsightSoftwareConsortium/itk-wasm#666]
It appears that the old version is still hardcoded here and used internally -- causing some issues with bundling internally. 

https://github.com/InsightSoftwareConsortium/itk-wasm/blob/f5d801e293924bf4c1f27a3b0cb099cbf9c14a85/src/itkConfigDevelopment.ts#L1

**Comment by thewtex** [comment]
@WillCMcC thanks for the report. #668 attempts to address this, but we will need to merged to see if it is effective.

**Comment by thewtex** [comment]
Addressed in 1.0.0-b.40 :tada:
