### ISSUE TITLE
Documentation not in sync with repo

### ISSUE THREAD

**Issue by dzenanz** [InsightSoftwareConsortium/itk-wasm#708]
At https://wasm.itk.org/examples/hello_world.html#Node-js, `index.mjs` has four lines of content:
```js
import path from 'path'
import { runPipelineNode } from 'itk-wasm'

const pipelinePath = path.resolve('web-build', 'hello')
runPipelineNode(pipelinePath)
```
whereas the current code has 5:
https://github.com/InsightSoftwareConsortium/itk-wasm/blob/f7fd69a57f015853fd1e4a3a559701c74f58e265/examples/hello-world/index.mjs#L1-L6

**Comment by thewtex** [comment]
This was addressed in #706 , deployment may still be in progress.
