### ISSUE TITLE
Webpack declares alias of "itkConfig.js" but is not referenced.

### ISSUE THREAD

**Issue by YeonHoJeong** [InsightSoftwareConsortium/itk-wasm#822]
Hello !

I'm trying to use itk-wasm, but I found that `ServiceWorker` is not being created.

I suspect that the reason I identified is that the webpack alias of `itkConfig.js `I declared is not reflected.

In `createWebWorkerPromise.js`, the config is treated as undefined and returns an error.

Is there any data to refer to or possible cause in this regard?

Thank you.

**Comment by thewtex** [comment]
Hello!

In recent versions of itk-wasm WebPack alias for `itkConfig.js` is not required. Instead, it is better to use `setPipelinesBaseUrl` and `setPipelineWorkerUrl`.

**Comment by YeonHoJeong** [comment]
@thewtex 

Thanks for your solution ! 

Then, do I have to call all other settings (imageIO, meshIO ...) by method like "pipelineWorkerUrl"? 

And is there a separate page that provides information about these initial configuration settings?

**Comment by thewtex** [comment]
> Then, do I have to call all other settings (imageIO, meshIO ...) by method like "pipelineWorkerUrl"?

Currently these are still overridden by itkConfig.js, but they will not need to be set separately from pipelinesBaseUrl.

> And is there a separate page that provides information about these initial configuration settings?

The documentation will be updated after image-io, mesh-io migration is complete. To summarize for each package (image-io and mesh-io are migrating to their own package per #716 ), the configuration setting will be:

1. getPipelinesBaseUrl on the package if defined
2. getPipelinesBaseUrl on the `itk-wasm` package if defined.
3. JsDeliver CDN hosting of the wasm modules by default.

**Comment by YeonHoJeong** [comment]
I found a solution to my problem.

In my project, I excluded node_modules in the "babel-loader" setting.

Accordingly, I changed itkConfig.js to common.js form.

In addition, the '@babel/plugin-transform-modules-commonjs' plugin was setup to have the process of transform the ESM to common.js.
