### ISSUE TITLE
Is it possible to build the module with system cbor?

### ISSUE THREAD

**Issue by pandas-a11y-11** [InsightSoftwareConsortium/itk-wasm#870]
It seems from the CMakeLists that this possibility is not considered for any dependency used here.

**Comment by thewtex** [comment]
Hi, what is your objective? A different version? Note that built webassembly modules are not going to use system libraries at runtime regardless.

**Comment by pandas-a11y-11** [comment]
A different version, yes. Since opening the issue, I've managed to link it, so might as well close the issue.
