### ISSUE TITLE
@itk-wasm/dicom readTags Typescript types are funny

### ISSUE THREAD

**Issue by PaulHax** [InsightSoftwareConsortium/itk-wasm#896]
Some bread crumbs for bleeding edge @itk-wasm/dicom readTags users.

`ReadDicomTagsOptions` Typescript type is a bit sparse at the moment. Its shape should be
```
interface ReadDicomTagsOptions {
    /** A JSON object with a "tags" array of the tags to read. If not provided, all tags are read. Example tag: "0008|103e". */
    tagsToRead?: { tags: Array<string> }
}
```

Usage
```
const result = await readDicomTags(
  this.webWorker,
  sanitizeFile(file),
  { tagsToRead: { tags: ["0008|103e"] } }
);

// @ts-expect-error @itk-wasm/dicom autogenerated types are WIP
const tagValues = new Map(result.tags);
```

**Comment by thewtex** [comment]
Can `{ tags: Array<string> }` please replace `Object` here?

https://github.com/InsightSoftwareConsortium/itk-wasm/blob/06a3ee26e499e59b426b2abee7db5b76f6b6baed/packages/dicom/typescript/src/read-dicom-tags-options.ts

And remove the comment from the top line?
